[build]
builder = "dockerfile"

[deploy]
releaseCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
startCommand = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --log-level info"

[env]
DJANGO_SETTINGS_MODULE = "core.settings"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
