[build]
builder = "dockerfile"

[deploy]
startCommand = "sh -c 'gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --log-level info'"

[env]
DJANGO_SETTINGS_MODULE = "core.settings"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"